name: RangedWolves
main: com.ACStache.RangedWolves.RangedWolves
version: 1.1
author: ACStache
description: Make Wolves attack your target on Ranged Attacks
softdepend: [MobArena]
commands:
    rw:
        description: reload the config or activate older wolves
        usage: |
               /rw reload               - Reload the Configuration
               /rw reloadMA             - Rerun the Mob Arena setup code
               /rw retro                - Add any surrounding wolves to their respective owner
permissions:
    RangedWolves.All:
        description: Unrestricted RangedWolves access (including reload commands)
        default: op
        children:
            RangedWolves.Unlimited: true
            RangedWolves.Reload: true
            RangedWolves.Worlds: true
            RangedWolves.Arenas: true
            RangedWolves.Creep: true
            RangedWolves.Retro: true
    RangedWolves.Unlimited:
        description: Allows uncapped number of tamed pet wolves
        default: op
    RangedWolves.Reload:
        description: Allows use of /rw reload & /rw reloadMA
        default: op
    RangedWolves.Retro:
        description: Allows use of /rw retro
        default: true
    RangedWolves.Worlds:
        description: Allows use of Ranged Wolves in any world
        default: true
    RangedWolves.Arenas:
        description: Allows use of Ranged Wolves in any arena
        default: true
    RangedWolves.Creep:
        description: Overrides config option to not have wolves attack creepers
        default: false