name: RangedWolves
main: com.ACStache.RangedWolves.RangedWolves
version: 0.7.3
author: ACStache
description: Make Wolves attack your target on Ranged Attacks
softdepend: [MobArena]
commands:
    rw:
        description: reload the config or activate older wolves
        usage: |
               /rw debug
               /rw reload
               /rw retro