name: RangedWolves
main: com.ACStache.RangedWolves.RangedWolves
version: 0.3
author: ACStache
description: Make Wolves attack your target on Ranged Attacks, IF in a Mob Arena
softdepend: [MobArena]
commands:
    rw:
        description: toggle debug mode on/off [currently unimplemented]
        usage: /rw debug